StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{64D93031A3800F1F}" {
   Id "ZICO-Execution"
   Target_en_us "EN Execution"
   Target_fr_fr "FR Execution"
   Modified 1691957857
   Author "tanin69"
   LastChanged "tanin69"
  }
  CustomStringTableItem "{64D9303191E28ACD}" {
   Id "ZICO-ExecutionTitle"
   Target_en_us "EN Execution Title"
   Target_fr_fr "FR Execution Title"
   Modified 1691957832
   Author "tanin69"
   LastChanged "tanin69"
  }
  CustomStringTableItem "{64D930320A73D361}" {
   Id "ZICO-Intel"
   Target_en_us "EN Intel"
   Target_fr_fr "FR Intel"
   Modified 1691958043
   Author "tanin69"
   LastChanged "tanin69"
  }
  CustomStringTableItem "{64D930320735E18F}" {
   Id "ZICO-IntelTitle"
   Target_en_us "EN Intel Title"
   Target_fr_fr "FR Intel Title"
   Modified 1691958023
   Author "tanin69"
   LastChanged "tanin69"
  }
  CustomStringTableItem "{64D9303178BBCC21}" {
   Id "ZICO-Mission"
   Target_en_us "EN Mission"
   Target_fr_fr "FR Mission"
   Modified 1691957789
   Author "tanin69"
   LastChanged "tanin69"
  }
  CustomStringTableItem "{64D930316D4DD413}" {
   Id "ZICO-MissionTitle"
   Target_en_us "EN Mission Title"
   Target_fr_fr "FR Mission Title"
   Modified 1691957760
   Author "tanin69"
   LastChanged "tanin69"
  }
  CustomStringTableItem "{64D93031E9246BF4}" {
   Id "ZICO-Signal"
   Target_en_us "EN Signal"
   Target_fr_fr "FR Signal"
   Modified 1691957982
   Author "tanin69"
   LastChanged "tanin69"
  }
  CustomStringTableItem "{64D93031B8A086CC}" {
   Id "ZICO-SignalTitle"
   Target_en_us "EN Signal Title"
   Target_fr_fr "FR Signal Title"
   Modified 1691957962
   Author "tanin69"
   LastChanged "tanin69"
  }
  CustomStringTableItem "{64D93037170C9FA3}" {
   Id "ZICO-Situation"
   Target_en_us "EN Situation"
   Target_fr_fr "FR Situation"
   Modified 1691957272
   Author "tanin69"
   LastChanged "tanin69"
  }
  CustomStringTableItem "{64D9303028240054}" {
   Id "ZICO-Situation-Title"
   Target_en_us "EN Situation Title"
   Target_fr_fr "FR Situation Title"
   Modified 1691957204
   Author "tanin69"
   LastChanged "tanin69"
  }
 }
}